name: Testing

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build build-essential
        
    - name: Configure CMake
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release
        
    - name: Build
      run: |
        cmake --build build
        
    - name: Run tests
      run: |
        cd build
        ./lambda_tests
        
    - name: Run main executable
      run: |
        cd build
        ./lambda